ShoppingDemo.App/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shopper.App.Models;
using ShoppingDemo.App.Data.Entites;
using ShoppingDemo.App.Mapping;
using ShoppingDemo.EFCore;
using Microsoft.AspNetCore.Authorization;

namespace ShoppingDemo.App.Controllers
{
    [Authorize]
    public class HomeController: Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IItemRepository _itemRepository;

         IMapper _mapper {get;set;}

        public HomeController(ILogger<HomeController> logger, 
        IItemRepository itemRepository)
        {
            _logger = logger;
            _mapper = new MapperConfiguration(cfg => cfg.AddProfile<EntityToQueryDtoMapper>()).CreateMapper();
            _itemRepository = itemRepository;

        }

        public IActionResult Index()
        {
            var items = _itemRepository.GetAll();
            var itemResults = _mapper.Map<IEnumerable<ItemModel>>(items);
            return View(itemResults);
        }

        public IActionResult Notfound()
        {
         
            return View();
        }

        public IActionResult UnderConstruction()
        {
         
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult ServerError()
        {
            return View();
        }

        



        
    }
}

ShoppingDemo.App/Controllers/ItemController.cs
using System;
using System.IO;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Shopper.App.Models;
using ShoppingDemo.App.Data.Entites;
using ShoppingDemo.App.Mapping;
using ShoppingDemo.App.Services;
using ShoppingDemo.EFCore;

namespace ShoppingDemo.App.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private readonly ILogger<ItemController> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        IMapper _mapper {get;set;}
        IItemService _itemService;

        public ItemController(ILogger<ItemController> logger, SignInManager<ApplicationUser> signInManager, IItemService itemService)
        {
            _logger = logger;
            _signInManager = signInManager;
            _mapper = new MapperConfiguration(cfg => cfg.AddProfile<EntityToQueryDtoMapper>()).CreateMapper();
            _itemService = itemService;
        }
        
        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddItemModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _itemService.CreateItem(model);
                    return RedirectToAction("Index","Home");
                }
                return View(model);

            }
            catch(IOException e)
            {
                ViewBag.Message = e.Message;
                return View(model);
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid Id)
        {
            var item = _itemService.FindItem(Id);
            if(item is null)
                return RedirectToAction("Not Found");
            return View(item);
        }

        [HttpPost]
        public IActionResult Delete(Item item)
        {
            _itemService.DeleteItem(item);
            return RedirectToAction("Index","Home");
         
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid Id)
        {
            var item = _itemService.FindItem(Id);
            if(item is null)
                return RedirectToAction("ResourceNotFound");
            
            return View(_mapper.Map<EditItemModel>(item));
        }

        [HttpPost]
        public IActionResult Edit(EditItemModel model)
        {
            _itemService.EditItem(model);
            return RedirectToAction("Index","Home");
         
        }


        public IActionResult ResourceNotFound()
        {
            return View();
        }

    }
}

ShoppingDemo.App/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Shopper.App.Models;
using ShoppingDemo.App.Data.Entites;
using ShoppingDemo.App.Mapping;
using ShoppingDemo.App.Services;
using ShoppingDemo.EFCore;

namespace ShoppingDemo.App.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly ILogger<ShoppingCartController> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        IShoppingCartService _shoppingCartService;
        IItemService _itemService;
        IMapper _mapper;

        public ShoppingCartController(ILogger<ShoppingCartController> logger, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IShoppingCartService shoppingCartService, IItemService itemService)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _shoppingCartService = shoppingCartService;
            _itemService = itemService;
            _mapper = new MapperConfiguration(cfg => cfg.AddProfile<EntityToQueryDtoMapper>()).CreateMapper();        
        }

        public IActionResult ViewCart()
        {
       
            var user = _userManager.GetUserAsync(User).Result;
            return View(_shoppingCartService.MapShoppingCartModel(user));

        }

        public IActionResult AddToCart(Guid Id)
        {
            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);
            var item = _itemService.FindItem(Id);
            return View(_mapper.Map<ItemModel>(item));
       
        }

        [HttpPost]
        public IActionResult AddToCart(ItemModel model)
        {
            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);

           _shoppingCartService.AddCartItem(cart, model);
            return RedirectToAction("ViewCart");
        }




        public IActionResult RemoveFromCart(Guid Id)
        {

            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);
            var item = _itemService.FindItem(Id);
            return View(_mapper.Map<ItemModel>(item));
     
        }
        [HttpPost]
        public IActionResult RemoveFromCart(ItemModel model)
        {
            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);
            _shoppingCartService.RemoveCartItem(cart, model);
            return RedirectToAction("ViewCart");
        }
    }
}

ShoppingDemo.App/Views/Home/index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using Microsoft.AspNetCore.Identity
@using Shopper.App.Models;
@model IEnumerable<ItemModel>;
@using ShoppingDemo.App;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@using ShoppingDemo.App.Data.Entites;

<style>
.card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
}

</style>

<h1>Browse Items</h1>


@if(!(Model.Count() == 0))
{

<div class="row">

  @foreach (var item in Model)
  {
      <section class="col-lg-3 col-md-6 py-3">
                        <div class="card">
                            <img src="@("~/Images/"+item.FileName)" asp-append-version="true" width="50px" height="50px" class="img-fluid card-img-top" />
                            <div class="card-body">
                                <h4 class="card-title">@item.Name</h4>
                                <small class="text-muted">$@item.Price </small>
                                <hr>
                                <p class="card-text">@if(String.IsNullOrEmpty(@item.Description))
                                    {
                                        <p>No description available.</p>
                                    }
                                    else{
                                        @item.Description
                                    }
                               </p>@if (SignInManager.IsSignedIn(User)){
                                     @if(item.inStock){
                <a class="btn btn-primary btn-sm" 
                      asp-controller="ShoppingCart"
                      asp-action="AddToCart"
                      asp-route-id="@item.Id"> <i style="font-size:10px" class="fa">&#xf07a;</i> Buy </a>
                  }}

@if(UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, AppConstants.AdminRole).Result)
 {  
                  <a class="btn btn-danger btn-sm" 
                      asp-controller="Item"
                      asp-action="Delete"
                      asp-route-id="@item.Id"> Delete </a>


                       <a class="btn btn-primary btn-sm" 
                      asp-controller="Item"
                      asp-action="Edit"
                      asp-route-id="@item.Id"> <i style="font-size:10px" class="fa">&#xf044;</i> Edit </a>}
                            </div>
                        </div>
             </section>
  }
    </div>

  
}
else
{
  <p>No items are available.</p>
}