ShoppingDemo.App/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shopper.App.Models;
using ShoppingDemo.App.Data.Entites;
using ShoppingDemo.App.Mapping;
using ShoppingDemo.App.Services;
using ShoppingDemo.EFCore;

namespace ShoppingDemo.App.Controllers
{
    [Authorize]
    public class OrderController :  Controller
    {

        private readonly ILogger<OrderController> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        ICustomerOrderService _customerComposition;
        IMapper _mapper;

        public OrderController(ILogger<OrderController> logger, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ICustomerOrderService customerComposition)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _customerComposition = customerComposition;
            _mapper = new MapperConfiguration(cfg => cfg.AddProfile<EntityToQueryDtoMapper>()).CreateMapper();
        }

        public IActionResult ViewOrders()
        {
         
            var user = _userManager.GetUserAsync(User).Result;
            return View(_customerComposition.GetOrders(user.Id));
    
        }


        public IActionResult ViewOrderDetail(Guid Id)
        {
            return View(_customerComposition.GetOrderDetails(Id));
        }


        public IActionResult PlaceOrder()
        {
            var user = _userManager.GetUserAsync(User).Result;
            return View(_customerComposition.MapOrderForm(user.Id));
        }

        [HttpPost]
        public IActionResult PlaceOrder(PlaceOrderModel model)
        {
            var user =_userManager.GetUserAsync(User).Result;

            var order = new Order();

            if(ModelState.IsValid)
            {
                _customerComposition.ProcessOrder(model,order,user);
                var errors = _customerComposition.GetModelErrors();
                if(errors.Count > 0)
                {
                    ViewBag.Message = _customerComposition.GetErrorMessage();
                    return View(model);
                }

                _customerComposition.SaveOrder(model,order,user.Id);
                return RedirectToAction("Index","Home");
            }
            return View(_customerComposition.MapOrderForm(user.Id));
        }


     
    
    }
}

ShoppingDemo.App/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Shopper.App.Models;
using ShoppingDemo.App.Data.Entites;
using ShoppingDemo.App.Mapping;
using ShoppingDemo.App.Services;
using ShoppingDemo.EFCore;

namespace ShoppingDemo.App.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly ILogger<ShoppingCartController> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        IShoppingCartService _shoppingCartService;
        IItemService _itemService;
        IMapper _mapper;

        public ShoppingCartController(ILogger<ShoppingCartController> logger, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IShoppingCartService shoppingCartService, IItemService itemService)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _shoppingCartService = shoppingCartService;
            _itemService = itemService;
            _mapper = new MapperConfiguration(cfg => cfg.AddProfile<EntityToQueryDtoMapper>()).CreateMapper();        
        }

        public IActionResult ViewCart()
        {
       
            var user = _userManager.GetUserAsync(User).Result;
            return View(_shoppingCartService.MapShoppingCartModel(user));

        }

        public IActionResult AddToCart(Guid Id)
        {
            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);
            var item = _itemService.FindItem(Id);
            return View(_mapper.Map<ItemModel>(item));
       
        }

        [HttpPost]
        public IActionResult AddToCart(ItemModel model)
        {
            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);

           _shoppingCartService.AddCartItem(cart, model);
            return RedirectToAction("ViewCart");
        }




        public IActionResult RemoveFromCart(Guid Id)
        {

            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);
            var item = _itemService.FindItem(Id);
            return View(_mapper.Map<ItemModel>(item));
     
        }
        [HttpPost]
        public IActionResult RemoveFromCart(ItemModel model)
        {
            var user = _userManager.GetUserAsync(User).Result;
            var cart = _shoppingCartService.GetShoppingCart(user);
            _shoppingCartService.RemoveCartItem(cart, model);
            return RedirectToAction("ViewCart");
        }
    }
}

ShoppingDemo.App/Views/ShoppingCart/AddToCart.cshtml
@using Shopper.App.Models;
@model ItemModel
@{
    ViewData["Title"] = "Add to Cart?";
}

<h1>Add @Model.Name to Cart?</h1>

<img src="@("~/Images/"+Model.FileName)" asp-append-version="true" width="200px" height="150px" />
<br></br>


     <form method="post">
                <div class="form-group">
                   <input type="submit" value="AddToCart"  class="btn btn-success"/>
                </div>
                <div>
       <a class="btn btn-secondary btn-sm" 
                      asp-controller="ShoppingCart"
                      asp-action="ViewCart"> Cancel </a>
                </div>
            

                
            </form>

ShoppingDemo.App/Views/ShoppingCart/RemoveFromCart.cshtml
@using Shopper.App.Models;
@model ItemModel
@{
    ViewData["Title"] = "Remove from Cart?";
}

<h1>Remove @Model.Name from Cart?</h1>

<img src="@("~/Images/"+Model.FileName)" asp-append-version="true" width="200px" height="150px" />
<br></br>


     <form method="post">
                <div class="form-group">
                   <input type="submit" value="Confirm"  class="btn btn-danger"/>
                </div>
                
           <div>
       <a class="btn btn-secondary btn-sm" 
                      asp-controller="ShoppingCart"
                      asp-action="ViewCart"> Cancel </a>
                </div>
                
            </form>
   

ShoppingDemo.App/Views/ShoppingCart/ViewCart.cshtml
@{
    ViewData["Title"] = "Shoppng Cart";
    decimal total =0;
}
@using Shopper.App.Models;
@model ShoppingCartModel;

<h1>Shopping Cart</h1>


@if(!(Model.Items.Count() == 0))
{
  <table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Image</th>
            <th scope="col"></th>
      <th scope="col"></th>


    </tr>
  </thead>
  <tbody>

    @foreach (var cartItem in Model.Items)
    {
    <tr>
      <td>@cartItem.Name</td>
      <td>$@cartItem.Price</td>
      <td>@cartItem.QuantityInCart</td>
       <td><img src="@("~/Images/"+cartItem.ImageFile)" asp-append-version="true" width="110px" height="80px" /></td>
      <td>
            <a class="btn btn-danger btn-sm" 
                      asp-controller="ShoppingCart"
                      asp-action="RemoveFromCart"
                      asp-route-id="@cartItem.ItemId"> Remove </a>
           </td>

        <td>
            <a class="btn btn-primary btn-sm" 
                      asp-controller="ShoppingCart"
                      asp-action="AddToCart"
                      asp-route-id="@cartItem.ItemId"> Add </a>
           </td>
      

    </tr>
        }
  </tbody>
</table>
<br>
<p>

  @foreach (var item in Model.Items)
  {
    total += item.Price*item.QuantityInCart;
  }
  Total: $@total
</p>
<br>

<a class="btn btn-primary btn-sm" 
                      asp-controller="Order"
                      asp-action="PlaceOrder"> Check Out </a>
}
else
{
  <p>No items are available.</p>
}